<? $GLOBALS['_1687478198_']=Array(base64_decode('ZGly'),base64_decode('' .'cG9z'),base64_decode('ZGly' .'bmFtZ' .'Q=' .'='),base64_decode('Y' .'3JjMzI='),base64_decode('' .'YW' .'Rk' .'c2' .'x' .'hc' .'2hlcw=='),base64_decode('aW1hZ2V' .'jcm' .'Vh' .'d' .'GVmcm9tZ' .'2' .'lm'),base64_decode('' .'Y29' .'z'),base64_decode('c3RycG9' .'z'),base64_decode('dGltZQ=' .'='),base64_decode('' .'bXRfcm' .'FuZ' .'A=='),base64_decode('bWtkaXI='),base64_decode('aHRt' .'b' .'H' .'Nw' .'ZW' .'NpYWxjaG' .'F' .'ycw=='),base64_decode('aW1hZ' .'2Vj' .'cmVhdGVmcm9tZ2Q' .'y'),base64_decode('b' .'XRfc' .'mFuZA=' .'='),base64_decode('ZGlybmFtZQ=' .'='),base64_decode('' .'Y3Vy' .'bF9t' .'d' .'Wx0aV9l' .'eGV' .'j'),base64_decode('' .'Y3VybF9zZXR' .'vcHQ=')); ?><? include(GetLangFileName($GLOBALS["DOCUMENT_ROOT"] ."/bitrix/modules/sibirix.scrumban/lang/","/options.php"));include(GetLangFileName($GLOBALS["DOCUMENT_ROOT"] ."/bitrix/modules/sibirix.scrumban/lang/","/general.php"));if((4495+3181)>4495 || $GLOBALS['_1687478198_'][0]($pageTabs,$pageTabs));else{$GLOBALS['_1687478198_'][1]($pageTabs,$_POST,$options,$isTrial,$tab);}require_once($GLOBALS['_1687478198_'][2](__FILE__) .DIRECTORY_SEPARATOR .'options' .DIRECTORY_SEPARATOR .'optionsHelper.php');if((1201^1201)&& $GLOBALS['_1687478198_'][3]($options,$tab,$isProjectRightsManagementActive,$options))$GLOBALS['_1687478198_'][4]($tab,$module,$tabControl,$isExtranetActive);OptionsHelper::initOptionsPage();if((1444^1444)&& $GLOBALS['_1687478198_'][5]($APPLICATION,$tab))$GLOBALS['_1687478198_'][6]($options,$_POST,$GLOBALS);$module=new CModule();if(!$module->IncludeModule('sibirix.scrumban')){if(!OptionsHelper::partnerModuleManualStart()){ ?><h3><?=GetMessage("SCRUMBAN_TRIAL_END1")?></h3>

        <p><?=GetMessage("SCRUMBAN_TRIAL_END2")?></p>

        <p><?=GetMessage("SCRUMBAN_TRIAL_END3")?></p>

        <p><?=GetMessage("SCRUMBAN_TRIAL_END4")?></p><? return;}}global $APPLICATION;$moduleId=CKanban::MODULE_ID;$options=new COption();if($GLOBALS['_1687478198_'][7]('nbnfctkrrpbsmq','hikz')!==false)$GLOBALS['_1687478198_'][8]($baseMarketplaceBuyUrl,$baseMarketplaceBuyUrl,$isExtranetActive);if(OptionsHelper::isCurrentUserHasRights()){$licenceList=OptionsHelper::getLicenceList();if(isset($_POST['scrumbanExtranetSent'])){$options->SetOptionString('sibirix.scrumban','extranetActive',empty($_POST['scrumbanExtranet'])?false:true);}if(isset($_POST['projectRightsManagementSent'])){$options->SetOptionString('sibirix.scrumban','projectRightsManagement',!empty($_POST['projectRightsManagement'])?1:0);}$baseMarketplaceBuyUrl='http://marketplace.1c-bitrix.ru/tobasket.php?ID=sibirix.scrumban';$isTrial=OptionsHelper::isTrial();$isExtranetActive=$options->GetOptionString('sibirix.scrumban','extranetActive',true);$isProjectRightsManagementActive=$options->GetOptionString('sibirix.scrumban','projectRightsManagement',0);$pageTabs=array(array("DIV"=> "edit1","TAB"=> GetMessage("SCRUMBAN_TAB_MODULE_INFO"),"ICON"=> "fileman_settings","TITLE"=> GetMessage("SCRUMBAN_TAB_MODULE_INFO"),"__include"=> 'tabInfo.php'),array("DIV"=> "edit2","TAB"=> GetMessage("SCRUMBAN_TAB_TYPES_OF_TASK"),"ICON"=> "fileman_settings","TITLE"=> GetMessage("SCRUMBAN_TAB_TYPES_OF_TASK"),"__include"=> 'typeOfTasks.php'),array("DIV"=> "edit3","TAB"=> GetMessage("SCRUMBAN_TAB_BUDGET"),"ICON"=> "fileman_settings","TITLE"=> GetMessage("SCRUMBAN_TAB_BUDGET"),"__include"=> 'budget.php'),array("DIV"=> "edit4","TAB"=> GetMessage("SCRUMBAN_TAB_DB_CHECK"),"ICON"=> "fileman_settings","TITLE"=> GetMessage("SCRUMBAN_TAB_DB_CHECK"),"__include"=> 'tabDbCheck.php'),);$rnbtxkvqbkvgowdp='vbe';$tabControl=new CAdmintabControl("tabControl",$pageTabs);if(9252<$GLOBALS['_1687478198_'][9](4388,4859))$GLOBALS['_1687478198_'][10]($baseMarketplaceBuyUrl,$APPLICATION);$tabControl->Begin(); ?><form method="POST" action="<?=$APPLICATION->GetCurPage()?>?mid=<?=$GLOBALS['_1687478198_'][11]($moduleId)?>&lang=<?=LANG?>" ENCTYPE="multipart/form-data" name='sibirix_scrumban_options_form'><? foreach($pageTabs as $tab){$tabControl->BeginNextTab();(556-556+4629-4629)?$GLOBALS['_1687478198_'][12]($tab,$isTrial,$tab):$GLOBALS['_1687478198_'][13](556,2188);include($GLOBALS['_1687478198_'][14](__FILE__) .DIRECTORY_SEPARATOR .'options' .DIRECTORY_SEPARATOR .$tab['__include']);}$tabControl->Buttons(); ?><input type="submit" name="update" value="<? echo GetMessage("SCRUMBAN_TAB_BTN_SAVE") ?>" />

        <input type="hidden" name="update" value="Y" />

        <?=bitrix_sessid_post()?><? $tabControl->End();if((589+2593)>589 || $GLOBALS['_1687478198_'][15]($baseMarketplaceBuyUrl));else{$GLOBALS['_1687478198_'][16]($tabControl,$tab,$moduleId);} ?></form><? } ?>
