ALTER TABLE `sib_kanban_project`
	ADD COLUMN `KANBAN_SYNC_TYPE` ENUM('0','1') NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `ARCHIVE_SPRINT_HIDE`;

ALTER TABLE `sib_kanban_column`
	ADD COLUMN `STAGE_ID` INT NULL AFTER `CUSTOMER_FINAL`,
	ADD COLUMN `STAGE_COLOR` CHAR(6) NULL AFTER `STAGE_ID`;
